### ISSUE TITLE
Cannot get real integer value when integer column set unsigned

### ISSUE THREAD

**Issue by pensz** [shyiko/mysql-binlog-connector-java#104]
example SQL:

```
CREATE TABLE `binlog_test` (
  `id` smallint(5) unsigned NOT NULL,
  `intid` int(10) unsigned DEFAULT NULL,
  `bigintid` bigint(20) unsigned DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

insert into binlog_test set id = 41002, intid=4294967293, bigintid=9223372036854775817;
```

in binlog, we can see such statement:

```
### INSERT INTO t_db.binlog_test
### SET
###   @1=-24534 (41002) /* SHORTINT meta=0 nullable=0 is_null=0 */
###   @2=-3 (4294967293) /* INT meta=0 nullable=1 is_null=0 */
###   @3=-9223372036854775799 (9223372036854775817) /* LONGINT meta=0 nullable=1 is_null=0 */
```

when we use WriteRowsEventData.getRows, we get the negative numers, not the real value.

**Comment by shyiko** [comment]
Hi.

This issue is mentioned in [readme.md/implementation-notes](https://github.com/shyiko/mysql-binlog-connector-java#implementation-notes). The problem is - binary log doesn't have information about whether column is unsigned or not and so there is no way for mysql-binlog-connector-java to do the conversion automatically. You'll have to read the column definition (using something similar to https://github.com/shyiko/mysql-binlog-connector-java/issues/24#issuecomment-43752483) and do the conversion yourself.
