### ISSUE TITLE
There's something seriously wrong with maven releases

### ISSUE THREAD

**Issue by snaury** [shyiko/mysql-binlog-connector-java#110]
When I download jars from search.maven.org, for example for 0.4.0 they don't match the code in the repository, with the diff of 1710 lines. For example released code does not have `updatePosition` and `advanceGTID` function and results in `getGtidSet` returning an incorrect set. Also `DumpBinaryLogGtidCommand` has `buffer.writeLong(interval.getEnd(), 8);` instead of `buffer.writeLong(interval.getEnd() + 1 /* right-open */, 8);`, which results in an incorrect set being sent to the server and is especially weird given that commit b97c3e14 was almost a year ago. Interestingly `advanceGTID` from 6b058b11 was also committed late September 2015.

Could you please check why such old and important commits could be missing in official releases?

**Comment by shyiko** [comment]
Hi @snaury. 0.4.0 was built from https://github.com/shyiko/mysql-binlog-connector-java/blob/0.4.0 (which is not based on master). I'll make a 0.4.1 hotfix with backported GTID-related changes. Thanks!

**Comment by shyiko** [comment]
0.4.1 published (see [release notes](https://github.com/shyiko/mysql-binlog-connector-java/compare/0.4.0...0.4.1)) (it should become available through Maven Central within the next ~2 hours). GTID auto-positioning deferred until 1.0.0 (as it may break existing clients depending on how they are used).

**Comment by shyiko** [comment]
btw, you can rely on https://github.com/shyiko/mysql-binlog-connector-java/blob/master/changelog.md (in master) as a source of truth. I try my best to keep it accurate.

**Comment by snaury** [comment]
Thank you very much, it works the way I expected now. Regarding 6b058b1 I'm going to track gtid set manually after all, since I need to synchronise commits across different systems and thus need to reliably know which transactions have actually been committed in that system to resume on restarts/etc.

Don't really understand your comment about compatibility and auto-positioning though, since now with 0.4.1 it's already possible to take `Executed_Gtid_Set` from `show master status` and position to it using `setGtidSet`, didn't that break compatibility, given gtid sets are now parsed and printed differently?

**Comment by shyiko** [comment]
@snaury yeah, auto-positioning itself isn't backward incompatible (and you can definitely do it manually). What I meant was this little piece of code - https://github.com/shyiko/mysql-binlog-connector-java/commit/6b058b115be857537f5f46af2ab8ec0eeb56a62d#diff-7addc4e3eed6e9254e088abc015ac8adR581 which automatically starts tracking gtid **instead of** binlog filename/position if gtid_mode is on. If I were to integrate this commit right away - people that don't specify binlogFilename/binlogPosition first time they connect might not expect gtid to kick in and would get incorrect binlogFilename/binlogPosition if they tried to use BinaryLogClient::getBinlogFilename()/getBinlogPosition(). I've a solution for that (removing "else" at https://github.com/shyiko/mysql-binlog-connector-java/blob/6b058b115be857537f5f46af2ab8ec0eeb56a62d/src/main/java/com/github/shyiko/mysql/binlog/BinaryLogClient.java#L702 should do it) but I want to test everything before making a new release. I'm just trying to minimize number of surprises for people using this project.

> didn't that break compatibility, given gtid sets are now parsed and printed differently

Technically :) it did but that was incorrect behavior on mysql-binlog-connect-java part which could result in lost events on reconnect. I'll make a note in the changelog.

Anyway, thank you for pointing that out :beer:
