### ISSUE TITLE
stop hiding binlog position?

### ISSUE THREAD

**Issue by osheroff** [shyiko/mysql-binlog-connector-java#130]
So I'm finally poking around at porting [maxwell](https://github.com/zendesk/maxwell) over to the binlog connector, but am having some issues around binlog positions.  Maxwell wants to know the precise position of a binlog event: it doesn't checkpoint its position until the binlog event has been serialized into JSON and written to Kafka, which is all done in an asynchronous callback codepath.  

The first thing I tried was to grab the current replication position via `client.getBinlogPosition` in the `onEvent` function, but that returns the position of the previous event.

Second, it looks like I can maybe just cast `EventHeader` into `EventHeaderV4` and get what I want out of it (although I'd love it if the filename was stashed away in there, too), but it feels somewhat nasty to reach over that barrier if I don't have to. 

Any concrete reason you're hiding the position information away?  Prevent folks from shooting themselves in the foot over table-map/write-rows coupled event madness?

**Comment by shyiko** [comment]
Hi @osheroff. It would be great to have you on board. 

That being said, the original idea was that at the time when listeners are executed they should see the current *(see footnote) position (an actual position of the event) (through BinaryLogClient::getBinlogFilename()/getBinlogPosition()). This is consistent with the way GTID is tracked (in a way that if you call BinaryLogClient::getGtidSet() while processing events you'll get gtid set which includes current transaction id but not the next one (in fact there is no "nextGtidSet" anywhere in the binlog for obvious reasons)).

If you need the position of the **next** event - then `((EventHeaderV4) event.getHeader()).getNextPosition()` + RotateEventData::getBinlogFilename()/getBinlogPosition() is at your disposal (as you have already noticed).

Let me know if something doesn't make sense or isn't clear. We're all reasonable people here :)

\* BinaryLogClient::getBinlogPosition() can potentially return previous position in cases that could otherwise lead to failures on reconnect (like advancing position on TABLE_MAP event + communication failure = inability to map tableId when deserializing *RowsEventData)

**Comment by osheroff** [comment]
ok, if you're good with `((EventHeaderV4) event.getHeader()).getNextPosition()` then I'm good.  thanks @shyiko.
