### ISSUE TITLE
Why is master so far from release?

### ISSUE THREAD

**Issue by georgewfraser** [shyiko/mysql-binlog-connector-java#141]
The master branch and hotfix-0.7.3 have diverged by many commits. It appears you are rebasing some (all?) commits on master onto a release branch. 

I have made some minor changes to my own fork of this repository. If I want to merge your changes, should I merge master or hotfix-0.7.3?

Please update the README to indicate which branch is appropriate for production use.

**Comment by shyiko** [comment]
Right now 0.x branche are stable. master contains upcoming (dev) changes and is not necessarily even working. I agree that it's kinda messy. Let me rename current master to develop and make latest hotfix branch master (so that PRs would be send against master as one would expect). I think it should eliminate the confusion. Thank you for putting a stop to it :)

**Comment by shyiko** [comment]
@georgewfraser done
