### ISSUE TITLE
Connect failed on GTID mode enabled.

### ISSUE THREAD

**Issue by PhantomThief** [shyiko/mysql-binlog-connector-java#156]
When calling:
binaryLogClient.setGtidSet(""); // enable gtid mode
binaryLogClient.connect();

the following exception.

com.github.shyiko.mysql.binlog.network.ServerException: The slave is connecting using CHANGE MASTER TO MASTER_AUTO_POSITION = 1, but the master has purged binary logs containing GTIDs that the slave requires.
        at com.github.shyiko.mysql.binlog.BinaryLogClient.listenForEventPackets(BinaryLogClient.java:734)
        at com.github.shyiko.mysql.binlog.BinaryLogClient.connect(BinaryLogClient.java:472)

actually I found when I setGtidSet, it wrongly set binlogFilename to "" and after connect it leads a wrong position.
so I have to setBinlogfilename(null) after setGtidSet, it works.

binlog-connector ver is 0.9.2.

**Comment by shyiko** [comment]
Hi @PhantomThief.

[binlogFilename](https://github.com/shyiko/mysql-binlog-connector-java/blob/0a4b6a62f52914e6cc8ebe7fd82067981362cc80/src/main/java/com/github/shyiko/mysql/binlog/BinaryLogClient.java#L261) "" and null yield different results. The behavior is [specified in javadocs](https://github.com/shyiko/mysql-binlog-connector-java/blob/0a4b6a62f52914e6cc8ebe7fd82067981362cc80/src/main/java/com/github/shyiko/mysql/binlog/BinaryLogClient.java#L308). In a nutshell (for simplicity let's assume binlogPosition is 4 (the beginning)):  
* "" gtid set + "" binary log filename = request binary logs from the very beginning. If gtid_purged is anything but empty connection will fail (because in this case server is missing some of records (purged range(s))).
* "" gtid set + null binary log filename = listen for binary logs events starting from the current (at the moment of connect) binary log filename and position.

I'm gonna update the javadocs to make it clear. 

I understand that there are valid cases when you are not really interested whether gtid_purged is empty or not and so I will also add `BinaryLogClient::gtidSetFallbackToPurged` (just make sure you read https://dev.mysql.com/doc/refman/5.7/en/replication-options-gtids.html#sysvar_gtid_purged so that the consequences of setting this parameter to true are clear).

**Comment by shyiko** [comment]
[0.11.0](https://github.com/shyiko/mysql-binlog-connector-java/blob/master/changelog.md#0110---2017-03-02) deployed to Maven Central :tada:

**Comment by PhantomThief** [comment]
Thanks a lot. I'll have a test next week:)
