### ISSUE TITLE
(MySQL 5.0.95) AuthenticationException: Unexpected authentication result (-2)

### ISSUE THREAD

**Issue by swordance** [shyiko/mysql-binlog-connector-java#20]
hi shyiko,

Thanks for your response.

Sorry I'm new to github, pasted the question to wrong issue. I deleted that one and open a new one for the problem.

The original post is here:
I encountered an exception thrown here. Wondering what caused authenticationResult[0]==(byte)0xFF. The user name&password is definitely correct, mysql server version is 5.0.95-log Source distribution. Is it mysql version related problem?

(new added comment: the code before and at BinaryLogClient:264)
if (authenticationResult[0] != (byte) 0x00 /\* ok /) {
if (authenticationResult[0] == (byte) 0xFF / error */) {
byte[] bytes = Arrays.copyOfRange(authenticationResult, 1, authenticationResult.length);
throw new AuthenticationException(new ErrorPacket(bytes).getErrorMessage());
}
throw new AuthenticationException("Unexpected authentication result (" + authenticationResult[0] + ")");
}

The exception I got is:

com.github.shyiko.mysql.binlog.network.AuthenticationException: Unexpected authentication result (-2)
    at com.github.shyiko.mysql.binlog.BinaryLogClient.connect(BinaryLogClient.java:264)
    at com.alipay.xflush.PrometheusTestMain.main(PrometheusTestMain.java:33)

The mysql-binlog-connector version I used is 0.1.0-SNAPSHOT.

**Comment by eduardohl** [comment]
I'm having this very same problem and having some trouble debugging it, wonder if anyone else had this problem or found a solution.

**Comment by eduardohl** [comment]
Finally found the problem.. due to MySQL older versions problem with password hashing (see: https://dev.mysql.com/doc/refman/5.6/en/password-hashing.html) my user's password was hashed using the pre-4.0 compatibility hash mode. Pretty hard to detect as most tools will just bypass the issue. In any case to fix it just: 
set @@session.old_passwords=0; SET PASSWORD FOR 'MYUSER'@'10.0.0.%' = PASSWORD('MYPASSWORD')

To check if this worked you can use: select Host, User, Password FROM mysql.user where User='MYUSER';, 
Old passwords will look like this: 6f8c114b58f2ce9e   
New passwords will look like this: *6BB4837EB74329105EE4568DDA7DC67ED2CA2AD9

Note: this can happen to mysql installations after 4.0, if the config session.old_passwords = 1

**Comment by shyiko** [comment]
Thank you for the info, @eduardohl!
