### ISSUE TITLE
sir,how I can know which table structure is changed?

### ISSUE THREAD

**Issue by 564064202** [shyiko/mysql-binlog-connector-java#246]

**Comment by bluebike** [comment]
From TABLE_MAP-events you can see column count + "partial" data types of table after alter.
From QUERY-DDL-events which you can parse changes.

Problem is that there is no easy way to see from binlog the (whole) current structure of table  (in given position) because TABLE_MAP-event doesn't contain field names. 

Mysql-server can handle this situation, because it parses and executes ALTER,CREATE,DROP (DDL) statements. 

But to handle table changes you have few ways:
1. Try to parse all  QUERY   ALTER,CREATE,DROP statements.
2. Look from master after seeing the alter event... as soon as possible that what is the state of table. 
But this is fragile, because there can be multiple alters in row.
3. Have a "sidecar" mysql/mariadb server where you execute just DDL-statements. 
In case ROW based logging almost all QUERY-statements should be grants or DDL statements
(I have thought this idea much).  This could even library version of server I think.

**Comment by shyiko** [comment]
https://github.com/shyiko/mysql-binlog-connector-java/pull/251 might also be of the interest.
