### ISSUE TITLE
How to handle binarylogclient connect during failovers

### ISSUE THREAD

**Issue by syed72** [shyiko/mysql-binlog-connector-java#25]
Hi
Locally Iam storing binlog details(name, position, serverid etc.,), to read binlogs from db cluster(i.e., master db).
If suppose any failover happens, and client connect to db cluster (but now to slave i.e., current master now), but the bin log details doesn't match with what we have locally. And when we try to connect with this, it get blocked in connect() method saying (connected to clusterip:port wit bin log name and position is bin.0000XX and YYYYYYY respectively). Please help me to handle the client connect when failover happens.

Thanks
Akram Syed

**Comment by inelation** [comment]
Hi @shyiko, in a similar fail-over situation but with GTIDs enabled, will the client be able to continue processing events from the newly promoted master? Contemplating on using a virtual ip / proxy or maybe the MySQL driver has fail-over support. I'm assuming yes and no duplicate events will be processed by the client when the old master comes back up and gets promoted due to the auto positioning and GTID sets tracked.  Your input would be greatly appreciated! Thank you for your time in advance!
