### ISSUE TITLE
How can I restore binlog position with a GTID ?

### ISSUE THREAD

**Issue by wenerme** [shyiko/mysql-binlog-connector-java#41]
If I enable the GTID, can I continue replication by last GTID instead of the binlog file and log position ?

**Comment by shyiko** [comment]
Hi.

Currently mysql-binlog-connector-java requests binary log with [COM_BINLOG_DUMP](http://dev.mysql.com/doc/internals/en/com-binlog-dump.html) ([DumpBinaryLogCommand.java](https://github.com/shyiko/mysql-binlog-connector-java/blob/master/src/main/java/com/github/shyiko/mysql/binlog/network/protocol/command/DumpBinaryLogCommand.java#L40) in mysql-binlog-connector-java codebase). In order to support GTID tailing it seems like all we need to do is to make use of [COM_BINLOG_DUMP_GTID](http://dev.mysql.com/doc/internals/en/com-binlog-dump-gtid.html). It hasn't been implemented yet, though.

**Comment by wenerme** [comment]
Event with  COM_BINLOG_DUMP_GTID, I still need the filename and position ?The filename and position is the same as non-GITD mode ?

**Comment by shyiko** [comment]
Looks like it. I'll try to implement COM_BINLOG_DUMP_GTID support in the next few days. Stay tuned :)

**Comment by wenerme** [comment]
From [this](http://www.percona.com/blog/2013/02/08/how-to-createrestore-a-slave-using-gtid-replication-in-mysql-5-6/) article,I think the filename and position is not needed in GTID mode.

**Comment by shyiko** [comment]
Yeah, I know they are not required (not allowed to be more specific) when setting up replication with GTID manually. But from http://dev.mysql.com/doc/internals/en/com-binlog-dump-gtid.html and (glancing over) client/mysqlbinlog.cc I see that both binlog filename and position have to be passed as part of payload. Thank you, anyway.
