### ISSUE TITLE
Why not support pull instead of push in BinaryLogClient ?

### ISSUE THREAD

**Issue by wenerme** [shyiko/mysql-binlog-connector-java#42]
This may solve a lot of problem, like #15 ,for currently Listener, I have to use a BlockingQueue to implement some pull style code.

**Comment by shyiko** [comment]
By #15 I'll assume #32 (as former isn't really related). 

In our case we needed to respond to the events as soon as they where arriving and the lion share of the time was spent on IO/deserialization rather than on "processing logic" so synchronous, push implementation was "just enough". Given different circumstances/requirements I might gone with NIO and pull approach but at that time it just wasn't important. Plus, one can always implement a different client leveraging everything else from the project. There isn't really anything that is somehow dependent on BinaryLogClient internals. Providing a different implementation should be relatively easy.
