### ISSUE TITLE
How to get the binlog file name corresponding to an Event?

### ISSUE THREAD

**Issue by ducaddepar** [shyiko/mysql-binlog-connector-java#54]
Is it possible to get the binlog file name corresponding to an Event object? There's the position in the EventHeader, but no file name.

**Comment by wushujames** [comment]
I did this in two parts:
1) Attach a lifecycle listener that implements onConnect() and grabs the initial binlog filename from the client. This gets you the initial binlog filename.
2) Handle the rotate event, which will tell you the filename of the next binlog.

**Comment by ducaddepar** [comment]
That sounds good, thanks!

**Comment by shyiko** [comment]
@ducaddepar @wushujames For the record, you can get it from BinaryLogClient::[getBinlogFilename](https://github.com/shyiko/mysql-binlog-connector-java/blob/master/src/main/java/com/github/shyiko/mysql/binlog/BinaryLogClient.java#L176)(). It's value changes with each incoming event.

**Comment by wushujames** [comment]
@shyiko Oh right, that's definitely the way to go if you have a reference to the BinaryLogClient. I had assumed @ducaddepar was asking about getting it within the context of an EventListener, where it's normally not exposed to you.

You bring up a good point tho. You could simply pass your BinaryLogClient to the EventListener, and grab the filename that way. That way, you don't need to handle ROTATE events.

**Comment by ducaddepar** [comment]
I was asking because it's unclear if BinaryLogClient getBinLogFileName() is thread-safe to access during onEvent(). But looks like it should be since the binary log client runs in one thread. Is that right?

**Comment by shyiko** [comment]
Both `binlogFilename` & `binlogPosition` are marked `volatile`. I believe that answers your question :)

**Comment by ducaddepar** [comment]
I think marking them volatile not necessarily make binlogFilename return the corresponding binlog file name of the event. If the client processes the binlog in two threads, while thread 1's onEvent() is invoked, thread 2 may modify binlogFilename, and so accessing binlogFilename in thread 1's onEvent() gives an inaccurate value.

**Comment by shyiko** [comment]
EventListeners are getting called in the same thread BinaryLogClient listens in, meaning you don't have to worry about thread safety unless you grab that piece of information from another thread (like through JMX). Because there is no point in setting a different binlogFilename other than before `connect` (in which case BinaryLogClient should not be running, thus not onEvent() can be called at this time) volatile does provide enough (visible reads) guarantee. 

NOTE: BinaryLogClient either uses the same thread it was `connect`ed in or a separate one in case of `connect(timeout)`. There are no other threads (except for a "keep alive" thread).
