### ISSUE TITLE
Way to read the binlog from the very beginning

### ISSUE THREAD

**Issue by shouichi** [shyiko/mysql-binlog-connector-java#71]
Hi, what's the way to read the binlog from the very beginning using GTID? I have workers need to replay all the events in MySQL for analyses. It'll be great if I can just specify the client to read from the oldest or the latest.

```
BinaryLogClient client = new BinaryLogClient("hostname", 3306, "username", "password");
client.setGtidSet("????");
```

Thanks for the great library :)

**Comment by shyiko** [comment]
Hi. You can [setGtidSet("")](https://github.com/shyiko/mysql-binlog-connector-java/blob/master/src/main/java/com/github/shyiko/mysql/binlog/BinaryLogClient.java#L269), but unless your are using 1.0.0-SNAPSHOT (GTID positioning is somewhat "sketchy" in <= 0.2.4) I would just setBinlogFilename("") to get the same result (you don't have use GtidSet just because gtid_mode is turned on in your MySQL server). To get the latest events use `null` instead of empty string (which in practice means - don't call setBinlogFilename at all).

**Comment by shouichi** [comment]
Thank you, worked perfectly!
