### ISSUE TITLE
Defining start and end position in the binlog to read from

### ISSUE THREAD

**Issue by flafson** [shyiko/mysql-binlog-connector-java#80]
First of all I wanted to thank you for all the work you have put up in this repository, this project is amazing.

Anyway, I'm trying to figure out if/how I can tell BinaryLogClient where to start reading and when to stop reading events.
What I'm trying to achieve is this, let's say I try to replicate from master to slave X amount of rows. At some point in time I realize there was a problem and not everything was replicated. I want to be able to tell BinaryLogClient to look inside a specific location (or range) and either try to replicate the rows that failed or do some kind of diagnostic on what happened there.

I know it's possible to get the binlog position and next position for every event, but I don't see how to tell it to run just a set number of events from a given position.

Another small note, it seems like BinaryLogClient works fine in reading all the events if you specify a correct position but doesn't read any events when the position is incorrect, is that on purpose? Wouldn't it make more sense to read anything from the next valid position?

Thanks!

**Comment by shyiko** [comment]
Hi. 

If you are interested only in a specific range you can opt for something like
```java
class RangeEventListener implements BinaryLogClient.EventListener {

    private BinaryLogClient binaryLogClient;
    private String filename;
    private long position;

    public RangeEventListener(BinaryLogClient binaryLogClient, String filename, long position) {
        this.binaryLogClient = binaryLogClient;
        this.filename = filename;
        this.position = position;
    }

    @Override
    public void onEvent(Event event) {
        if (filename.equals(binaryLogClient.getBinlogFilename()) &&
            position <= binaryLogClient.getBinlogPosition()) {
            try {
                binaryLogClient.disconnect();
            } catch (IOException e) {
                throw new RuntimeException(e);
            }
        }
    }
}

BinaryLogClient binaryLogClient = new BinaryLogClient("username", "password");
binaryLogClient.setBinlogFilename("mysql-bin.000003");
binaryLogClient.setBinlogPosition(4);
binaryLogClient.registerEventListener(new RangeEventListener(binaryLogClient, 
    "mysql-bin.000004", 57));
binaryLogClient.connect();
```

or 

```java
class SeqEventListener implements BinaryLogClient.EventListener {

    private BinaryLogClient binaryLogClient;
    private int disconnectAfter;

    public SeqEventListener(BinaryLogClient binaryLogClient, int disconnectAfter) {
        this.binaryLogClient = binaryLogClient;
        this.disconnectAfter = disconnectAfter;
    }

    @Override
    public void onEvent(Event event) {
        if (--disconnectAfter == 0) {
            try {
                binaryLogClient.disconnect();
            } catch (IOException e) {
                throw new RuntimeException(e);
            }
        }
    }
}

...
binaryLogClient.registerEventListener(new SeqEventListener(binaryLogClient, 3));
binaryLogClient.connect();
```

As for "doesn't read any events when the position is incorrect" - behavior of the BinaryLogClient is tied directly to the binary log stream. Once BinaryLogClient has issued BINLOG_DUMP command it starts reading the data and unless MySQL has replied with some kind of error there is no way for us to know that something isn't right (apart from connection state). Honestly, I don't really remember the exact behavior but I think you should get an exception right away. If you are not getting any - please let me know.

The responsibility to determine "next valid position" is left to the user because of 2 reasons: it's very easy and only the client knows what is the correct response to wrong binlogFilename/binlogPosition (resume from the oldest binlog? resume from the beginning (position 4) of the same binlog file? how about most recent log? bail out completely?). One more thing, let's say we have 3 events: at position 4, 57 and 108. If you are trying to connect at 70 and would like to skip to the "next valid position" within same binlog (108) there is no other way other than to connect at the beginning (position 4) and discard all the data up until you hit event with position higher than the requested. If binary log is really big - that can mean a lot of wasted traffic.

Anyway, please let me know if you have any other questions. Cheers!

**Comment by flafson** [comment]
Thanks for the really quick and extremely helpful response. I really appreciate it.

The code snippets work great, thanks.

As for the valid position, if you give it an invalid position, it would read ROTATE and FORMAT_DESCRIPTION events but nothing afterwards and it will just hang and wait.

Took me a while to figure out that I was seeing this behavior because the position was wrong, I thought the way I used the library was wrong.

**Comment by shyiko** [comment]
I see. Alright, I'll try to come up with something more intuitive as part of #37. Thank you for bringing it up!
